version: '3'

services:
  app:
    container_name: eb-app
    build:
      context: ./docker
    ports:
      - "5001:5000"
    volumes:
      - ./app:/app
    depends_on:
        - db

  db:
    container_name: eb-db
    image: mysql:5.7
    restart: always
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/db/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cashbook
      MYSQL_USER: klab
      MYSQL_PASSWORD: klab
    ports:
      - "3306:3306"
